branches:
  only:
    - master

language: rust
rust:
  - 1.31.0
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose
  - cargo test --verbose

jobs:
  include:
    - name: rustfmt
      rust: 1.31.0

      install:
        - rustup component add rustfmt

      script:
        - cargo fmt -- --check

    - name: clippy
      rust: 1.31.0

      install:
        - rustup component add clippy-preview

      script:
        - cargo clippy
